spring.datasource.url=jdbc:mysql://bkh7y2t2xuatz6fy7miv-mysql.services.clever-cloud.com:3306/bkh7y2t2xuatz6fy7miv
spring.datasource.username=ua9zndzttz5cpyqn
spring.datasource.password=uS504kESHumMfzqH4qjm

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080